### ISSUE TITLE
vpn.ycp.edu

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [dlenski/what-vpn#10]
[VPN (virtual private network)](https://ltshelp.ycp.edu/vpn) suggests they do have a Fortinet VPN and I can ping server `vpn.ycp.edu`. However, I cannot connect to port 443:
```
$ telnet vpn.ycp.edu 443
Trying 192.245.87.2...
telnet: Unable to connect to remote host: Connection timed out
$ 
```
They might be filtering IP addresses. I suggest this server is removed from the tests.

**Comment by dlenski** [comment]
It works fine in the recent CI runs (https://github.com/dlenski/what-vpn/runs/6762118550?check_suite_focus=true#step:5:30) and on my laptop.

There are only a limited number of candidates I can find for each protocol, which are (a) reasonably public and (b) reasonably large institutions and (c) hopefully not going to make a big deal out of a few packets being sent to them now and then for purposes of researching and studying VPN protocols.

**Comment by DimitriPapadopoulos** [comment]
Still, I cannot connect so I cannot run the tests. Perhaps they are limited to US IP addresses.
```
$ what-vpn -v -K vpn.ycp.edu

Sniffing vpn.ycp.edu ...
  Is it AnyConnect/OpenConnect? timeout
  Is it Juniper/Pulse? timeout
  Is it PAN GlobalProtect? timeout
  Is it Barracuda? timeout
  Is it Check Point? timeout
  Is it SSTP? timeout
  Is it OpenVPN? timeout
  Is it Fortinet? timeout
  Is it Array Networks? timeout
  Is it F5 BigIP? timeout
  Is it SonicWall NX? timeout
  Is it Aruba VIA? timeout
  => timeout
$ 
```

**Comment by dlenski** [comment]
I am in :canada:, for what it's worth. Looking at the commit dates, I'm almost certain I've run the test suite while in :eu: or :israel:, but that was several years and many revisions of the target list ago. :man_shrugging:
