### ISSUE TITLE
sslvpn.co.adams.il.us

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [dlenski/what-vpn#12]
I cannot ping `sslvpn.co.adams.il.us` and I cannot connect to port 443:
```
$ telnet sslvpn.co.adams.il.us 443
Trying 206.71.192.217...
telnet: Unable to connect to remote host: Connection timed out
$ 
```

According to [VPN access with Cisco AnyConnect VPN (Windows)](https://howto.adams.edu/VPN_access_with_Cisco_AnyConnect_VPN_(Windows)), the actual VPN gateway might be `vpn1.adams.edu` instead, but:
```
$ telnet vpn1.adams.edu 443
Trying 192.156.134.118...
telnet: Unable to connect to remote host: No route to host
$ 
```

**Comment by dlenski** [comment]
As with #10, [it works fine from CI](https://github.com/dlenski/what-vpn/runs/6762118550?check_suite_focus=true#step:5:52), as well as from every other point of Internet connectivity that I've run the tests from.

**Comment by DimitriPapadopoulos** [comment]
They may filter out non-US IP addresses. It's not available from multiple Internet providers in France. Whatever I try:
```
$ what-vpn -v -K sslvpn.co.adams.il.us

Sniffing sslvpn.co.adams.il.us ...
  Is it AnyConnect/OpenConnect? timeout
  Is it Juniper/Pulse? timeout
  Is it PAN GlobalProtect? timeout
  Is it Barracuda? timeout
  Is it Check Point? timeout
  Is it SSTP? timeout
  Is it OpenVPN? timeout
  Is it Fortinet? timeout
  Is it Array Networks? timeout
  Is it F5 BigIP? timeout
  Is it SonicWall NX? timeout
  Is it Aruba VIA? timeout
  => timeout
$ 
```
