### ISSUE TITLE
VPN port other than 443

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [dlenski/what-vpn#2]
How do I specify a port different from 443?

I would need that for the VPNs described here:
* https://docinfo.univ-rennes1.fr/acces-distant-vpn-avec-fortinet-sous-linux
* https://www.ed.ac.uk/information-services/computing/desktop-personal/vpn
* https://www2.physics.ox.ac.uk/it-services/vpn-fortigate

**Comment by dlenski** [comment]
> How do I specify a port different from 443?

`what-vpn host:port`

**Comment by DimitriPapadopoulos** [comment]
Then can I change the help message from `server` to `server[:port]`?
```
usage: what-vpn [-h] [-k] [-K] [-t SEC] [-v | -c] [-L] [-V] [--ssl3 | --tlsv1 | --tlsv11] [-S SNIFFER] [-P PROXY]
                server [server ...]
```

**Comment by DimitriPapadopoulos** [comment]
Unfortunately, I don't think the help automatically generated by `argparse.ArgumentParser()` can be modified.

**Comment by dlenski** [comment]
Yes, you just need to add `metavar="server[:port]"` to the relevant `add_argument`. 89ac7d6:

```
$ what-vpn 
usage: what-vpn [-h] [-k] [-K] [-t SEC] [-v | -c] [-L] [-V]
                [--ssl3 | --tlsv1 | --tlsv11] [-S SNIFFER] [-P PROXY]
                server[:port] [server[:port] ...]
what-vpn: error: the following arguments are required: server[:port]
```

**Comment by DimitriPapadopoulos** [comment]
Ah, works great indeed. It's a pity `metavar` is not documented.

**Comment by DimitriPapadopoulos** [comment]
It is actually well documented in the [`optparse`](https://docs.python.org/3/library/optparse.html) tutorial:
> There’s a lot going on here to help [optparse](https://docs.python.org/3/library/optparse.html#module-optparse) generate the best possible help message:
> [...]
> * options that take a value indicate this fact in their automatically-generated help message, e.g. for the “mode” option:
>   `-m MODE, --mode=MODE`
>   Here, “MODE” is called the meta-variable: it stands for the argument that the user is expected to supply to `-m/--mode`. By default, [optparse](https://docs.python.org/3/library/optparse.html#module-optparse) converts the destination variable name to uppercase and uses that for the meta-variable. Sometimes, that’s not what you want—for example, the `--filename` option explicitly sets `metavar="FILE"`, resulting in this automatically-generated option description:
>   `-f FILE, --filename=FILE`

It is more difficult to find in the [`argparse`](https://docs.python.org/3/library/argparse.html#metavar) reference documentation.
